# Generated by Django 5.0.4 on 2024-05-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='lasttName',
            new_name='lastName',
        ),
    ]
